export const seoPages = [
  {
    slug: 'tile-installation-eugene',
    title: 'Professional Tile Installation in Eugene, OR | Halleman Construction',
    description: 'Expert tile installation services in Eugene, Oregon. Kitchen backsplashes, bathroom floors, shower surrounds. Licensed contractor with 15+ years experience.',
    h1: 'Professional Tile Installation Services in Eugene, OR',
    service: 'Tile Installation',
  },
  {
    slug: 'kitchen-remodeling-eugene',
    title: 'Kitchen Remodeling Eugene OR | Custom Kitchen Renovation',
    description: 'Transform your kitchen with professional remodeling services in Eugene. Custom cabinets, countertops, tile work. Licensed & insured contractor.',
    h1: 'Kitchen Remodeling Services in Eugene, Oregon',
    service: 'Kitchen Remodeling',
  },
  {
    slug: 'bathroom-renovation-eugene',
    title: 'Bathroom Renovation Eugene OR | Complete Bathroom Remodeling',
    description: 'Complete bathroom renovation services in Eugene, OR. Showers, tubs, tile, vanities, lighting. Professional licensed contractor.',
    h1: 'Bathroom Renovation & Remodeling in Eugene, OR',
    service: 'Bathroom Renovation',
  },
  {
    slug: 'deck-builder-eugene',
    title: 'Deck Builder Eugene OR | Custom Deck Construction',
    description: 'Professional deck building in Eugene, Oregon. Custom designs, quality materials, expert craftsmanship. Licensed deck contractor.',
    h1: 'Custom Deck Building Services in Eugene, OR',
    service: 'Deck Construction',
  },
  {
    slug: 'fence-installation-eugene',
    title: 'Fence Installation Eugene OR | Wood & Vinyl Fencing',
    description: 'Expert fence installation in Eugene. Privacy fences, picket fences, vinyl fencing. Licensed contractor with quality materials.',
    h1: 'Professional Fence Installation in Eugene, Oregon',
    service: 'Fence Installation',
  },
  {
    slug: 'patio-cover-eugene',
    title: 'Patio Covers Eugene OR | Custom Covered Patios',
    description: 'Custom patio cover installation in Eugene, OR. Extend your outdoor living space with professional patio covers.',
    h1: 'Patio Cover Installation Services in Eugene, OR',
    service: 'Patio Covers',
  },
  {
    slug: 'tile-installation-cottage-grove',
    title: 'Tile Installation Cottage Grove OR | Professional Tile Contractor',
    description: 'Expert tile installation in Cottage Grove, Oregon. Kitchen, bathroom, and floor tile services. Licensed contractor.',
    h1: 'Tile Installation Services in Cottage Grove, OR',
    service: 'Tile Installation',
  },
  {
    slug: 'kitchen-remodeling-cottage-grove',
    title: 'Kitchen Remodeling Cottage Grove OR | Kitchen Renovation',
    description: 'Professional kitchen remodeling in Cottage Grove. Custom cabinets, countertops, complete renovations.',
    h1: 'Kitchen Remodeling in Cottage Grove, Oregon',
    service: 'Kitchen Remodeling',
  },
  {
    slug: 'bathroom-renovation-cottage-grove',
    title: 'Bathroom Renovation Cottage Grove OR | Bathroom Remodeling',
    description: 'Complete bathroom renovation services in Cottage Grove, OR. Licensed contractor with expert craftsmanship.',
    h1: 'Bathroom Renovation Services in Cottage Grove, OR',
    service: 'Bathroom Renovation',
  },
  {
    slug: 'deck-builder-cottage-grove',
    title: 'Deck Builder Cottage Grove OR | Custom Decks',
    description: 'Professional deck building in Cottage Grove, Oregon. Custom designs and quality construction.',
    h1: 'Custom Deck Building in Cottage Grove, OR',
    service: 'Deck Construction',
  },
  {
    slug: 'tile-installation-veneta',
    title: 'Tile Installation Veneta OR | Expert Tile Contractor',
    description: 'Professional tile installation services in Veneta, Oregon. Kitchen backsplashes, bathroom tile, flooring.',
    h1: 'Tile Installation Services in Veneta, OR',
    service: 'Tile Installation',
  },
  {
    slug: 'kitchen-remodeling-veneta',
    title: 'Kitchen Remodeling Veneta OR | Kitchen Renovation Services',
    description: 'Transform your kitchen with professional remodeling in Veneta. Licensed contractor with quality work.',
    h1: 'Kitchen Remodeling Services in Veneta, Oregon',
    service: 'Kitchen Remodeling',
  },
  {
    slug: 'bathroom-renovation-veneta',
    title: 'Bathroom Renovation Veneta OR | Complete Bathroom Remodeling',
    description: 'Expert bathroom renovation in Veneta, OR. Complete remodeling services from licensed contractor.',
    h1: 'Bathroom Renovation in Veneta, Oregon',
    service: 'Bathroom Renovation',
  },
  {
    slug: 'tile-installation-coburg',
    title: 'Tile Installation Coburg OR | Professional Tile Services',
    description: 'Expert tile installation in Coburg, Oregon. Quality tile work for kitchens, bathrooms, and floors.',
    h1: 'Tile Installation Services in Coburg, OR',
    service: 'Tile Installation',
  },
  {
    slug: 'kitchen-remodeling-coburg',
    title: 'Kitchen Remodeling Coburg OR | Kitchen Renovation',
    description: 'Professional kitchen remodeling services in Coburg. Custom designs and quality craftsmanship.',
    h1: 'Kitchen Remodeling in Coburg, Oregon',
    service: 'Kitchen Remodeling',
  },
  {
    slug: 'bathroom-renovation-coburg',
    title: 'Bathroom Renovation Coburg OR | Bathroom Remodeling',
    description: 'Complete bathroom renovation in Coburg, OR. Licensed contractor with expert remodeling services.',
    h1: 'Bathroom Renovation Services in Coburg, OR',
    service: 'Bathroom Renovation',
  },
  {
    slug: 'home-remodeling-lane-county',
    title: 'Home Remodeling Lane County OR | Complete Home Renovation',
    description: 'Professional home remodeling throughout Lane County, Oregon. Kitchen, bathroom, and complete home renovations.',
    h1: 'Home Remodeling Services in Lane County, Oregon',
    service: 'Home Remodeling',
  },
  {
    slug: 'licensed-contractor-eugene',
    title: 'Licensed Contractor Eugene OR | Bonded & Insured Construction',
    description: 'Licensed, bonded, and insured contractor in Eugene, Oregon. Quality construction and remodeling services.',
    h1: 'Licensed Contractor Services in Eugene, OR',
    service: 'General Contracting',
  },
  {
    slug: 'outdoor-living-eugene',
    title: 'Outdoor Living Spaces Eugene OR | Decks, Patios, Outdoor Kitchens',
    description: 'Create your dream outdoor living space in Eugene. Decks, patios, patio covers, and outdoor construction.',
    h1: 'Outdoor Living Space Construction in Eugene, OR',
    service: 'Outdoor Living',
  },
]